version: '3.8'
services:
  backend:
    build: ./feedback-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
    networks:
      - feedback-net

  frontend:
    build: ./feedback-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - feedback-net

networks:
  feedback-net: